# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scuby-wars}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andi Bade", "Dirk Breuer", "Sebastian Cohnen"]
  s.date = %q{2011-01-09}
  s.description = %q{Library for programming little AI-Bots, fighting against each other}
  s.email = %q{andi@galaxycats.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "example_bots/shot_and_run.rb",
     "lib/scruby_wars.rb",
     "lib/scuby-wars.rb",
     "lib/scuby_wars/client.rb",
     "lib/scuby_wars/monitor.rb",
     "node-server/express_server.js",
     "node-server/lib/grasshopper.js",
     "node-server/public/explosion.png",
     "node-server/public/monster.js",
     "node-server/public/panzer.png",
     "node-server/public/raphael.min.js",
     "node-server/views/index.ejs",
     "scuby-wars.gemspec"
  ]
  s.homepage = %q{http://github.com/galaxycats/scuby-wars}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Library for programming little AI-Bots, fighting against each other}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.7.8"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.3"])
    else
      s.add_dependency(%q<yajl-ruby>, [">= 0.7.8"])
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_dependency(%q<i18n>, [">= 0.5.0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.3"])
    end
  else
    s.add_dependency(%q<yajl-ruby>, [">= 0.7.8"])
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
    s.add_dependency(%q<i18n>, [">= 0.5.0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.3"])
  end
end

